name: Enforce PR source branch

on:
  pull_request:
    branches: [ main ]

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from development
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != "development" ]]; then
            echo "Pull request must come from 'development' branch!"
            exit 1
          fi

