name: Enforce PR source branch

on:
  pull_request:
    branches: [ main ]

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from development
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != "development" ]]; then
            echo "Pull request must come from 'development' branch!"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: check-source
    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_DEV: "false"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/cstefc/focus_track_ui:${{ github.sha }} .

      - name: Tag latest
        run: docker tag ghcr.io/cstefc/focus_track_ui:${{ github.sha }} ghcr.io/cstefc/focus_track_ui:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/cstefc/focus_track_ui:${{ github.sha }}
          docker push ghcr.io/cstefc/focus_track_ui:latest
